<div  id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
	    <input type="hidden" name="payment[ecpay_choosen_payment]" title="Ecpaypayment" value="credit">
</div>
<?php echo '<div class="form-alt" style="font-size:small;text-align:center;">' . $this->__('You will be redirected to the ECPay website.') . '<BR>' . 
		$this->__('Transaction will be processed in New Taiwan Dollars ($NT)') . '</div>'; ?>
