<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div class="field">
        <div class="input-box">
            <select name="payment[ecpay_choosen_payment]" class="validate-select validation-passed" title="Ecpaypayment">
                <?php
                    $ecpayPaymentMethods = $this->getMethod()->getConfigData('ecpay_payment_methods');
                    $list = explode(',', $ecpayPaymentMethods);
                    if (in_array('credit', $list)) {
                        echo '<option value="credit">信用卡(一次付清)</option>';
                    }

                    if (in_array('credit_3', $list)) {
                        echo '<option value="credit_3">信用卡(3期)</option>';
                    }

                    if (in_array('credit_6', $list)) {
                        echo '<option value="credit_6">信用卡(6期)</option>';
                    }

                    if (in_array('credit_12', $list)) {
                        echo '<option value="credit_12">信用卡(12期)</option>';
                    }

                    if (in_array('credit_18', $list)) {
                        echo '<option value="credit_18">信用卡(18期)</option>';
                    }

                    if (in_array('credit_24', $list)) {
                        echo '<option value="credit_24">信用卡(24期)</option>';
                    }

                    if (in_array('webatm', $list)) {
                        echo '<option value="webatm">網路ATM</option>';
                    }

                    if (in_array('atm', $list)) {
                        echo '<option value="atm">ATM</option>';
                    }

                    if (in_array('barcode', $list)) {
                        echo '<option value="barcode">超商條碼</option>';
                    }

                    if (in_array('cvs', $list)) {
                        echo '<option value="cvs">超商代碼</option>';
                    }
                ?>
            </select>
        </div>
    </div>
</div>